stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ROS_DISTRO: humble

image: ros:${ROS_DISTRO}-ros-base

before_script:
  - apt-get update
  - rosdep install --from-paths src --ignore-src -r -y
  - source /opt/ros/${ROS_DISTRO}/setup.bash

build:
  stage: build
  tags:
    - docker
  script:
    - colcon build --packages-select interfaces
    - source install/setup.bash
    - colcon build

test:
  stage: test
  tags:
    - docker
  script:
    - colcon build
    - colcon test
